version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:8.3.3
    networks:
      - es-utils-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-disk:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana_container
    image: kibana:8.3.3
    networks:
      - es-utils-network
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  es-disk:
    driver: local
networks:
  es-utils-network:

