# N.B. I will use PHP8.0 from my host not docker
version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:7.14.0
    networks:
      - backend
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-disk:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana_container
    image: kibana:7.14.0
    networks:
      - backend
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  es-disk:
    driver: local
networks:
  backend:

