name: Auto-fromats the code
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!develop'
jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install requirements
        run: composer install

      - name: Run PHP CS Fixer
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
